### ISSUE TITLE
XCode 7.2 support / Поддержка XCode 7.2

### ISSUE THREAD

**Issue by linxfather** [bealex/AwesomeTableAnimationCalculator#1]
Swift syntax is not compatible for XCode 7.2

Проект не компилируется в XCode 7.2

**Comment by bealex** [comment]
Добрый день!

Да, я использую появившиеся в Xcode 7.3 способы описания, в частности, associated types. Это сделано намеренно, так как 7.3 уже «в релизе»

**Comment by linxfather** [comment]
Однако это снижает круг целевой аудитории, так как требуется обновить операционку чтобы поставить XCode 7.3.

Странно что нет OBJC версии сабжа. Ибо кто бы что не говорил OBJC достаточно полноценен.

**Comment by bealex** [comment]
Я сейчас не планирую поддерживать более старые версии Swift.

Objective-C более-менее поддерживается, я в статье https://habrahabr.ru/company/redmadrobot/blog/282509/ я указываю, как это можно сделать. Вести параллельно две версии алгоритма я тоже пока не планирую.

**Comment by linxfather** [comment]
`Я сейчас не планирую поддерживать более старые версии Swift.`
https://habrahabr.ru/company/redmadrobot/blog/282509/
`Конечно же, фреймворк в первую очередь решает мои собственные задачи. **Если вам вдруг нужна фича, которая сейчас там отсутствует**, пишите, спрашивайте, попробую доработать.`

вот я и написал что код несовместим с текущим мейнстримом, к которому я отношусь. И получается ваши "старания" останутся вашими.

**Comment by bealex** [comment]
Не совсем понимаю, что вы понимаете под текущим мейнстримом, к которому вы относитесь.

PS. Сделайте форк и поменяйте associatedtype на typealias в `ACellSectionModel.swift`, сделать быстрее, чем обсуждать :-)
