### ISSUE TITLE
Связь ASectionModel и ACellModel

### ISSUE THREAD

**Issue by phantomato** [bealex/AwesomeTableAnimationCalculator#2]
Привет! Столкнулся с траблой, где нужно определить имеется ли уже определенный элемент (ACellModel) в модели, а если есть, то узнать в какой секции. Я стал перебирать sections в модели, и выяснилось, что у нее нету связи с моделями ячеек. Пробовал перебирать items, у них тоже никаких связей с секциями не оказалось. Было бы здорово увидеть подобные связи в публичном API.

**Comment by bealex** [comment]
Привет!
Добавил соответствующие методы в калькулятор. v0.9.13
