### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by phantomato** [bealex/AwesomeTableAnimationCalculator#4]
Хотелось бы иметь поддержку Swift 3.0, хотя бы на отдельной ветке. Спасибо!

**Comment by bealex** [comment]
Куда оно денется, будет. Не хочу бежать, пока хотя бы еще пара бет не пройдёт. А там — обязательно.

**Comment by phantomato** [comment]
а теперь?

**Comment by bealex** [comment]
Обновил все под Swift 3. Cocoapods пока, судя по тому, что я вижу, не дружат нормально с Xcode 8, поэтому обновить подспек у них в репозитории не получилось. А Carthage, по-идее, должен работать уже. :)
